_BASE_: "./Base-DensePose-RCNN.yaml"
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
MODEL:

  MASK_ON: False
  KEYPOINT_ON: True
  DENSEPOSE_ON: True
  ROI_BOX_HEAD:
    SMOOTH_L1_BETA: 0.5
  ROI_DENSEPOSE_HEAD:
    NAME: "DensePoseAMAHead"
    INTER_WEIGHTS: 0.5
    RCNN_HEAD_ON: True
    SEMSEG_WEIGHTS: 1.0
    CONV_HEAD_DIM: 256
    POOLER_RESOLUTION: 32
    HEATMAP_SIZE: 64
    SEMSEG_ON: False
    IA_LOSS: False
    KPT_ON: True
    KPT_UP_SCALE: 1
    FG_IOU_THRESHOLD: 0.65
    PREDICTOR: "TaskTransformerAMAPredictorV2"

  ROI_KEYPOINT_HEAD:
    LOSS_WEIGHT: 0.5
  RPN:
    PRE_NMS_TOPK_TRAIN: 1200  # Per FPN level
    PRE_NMS_TOPK_TEST: 1000  # Per FPN level
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
      BATCH_SIZE_PER_IMAGE: 384
SOLVER:
  MAX_ITER: 260000
  STEPS: (200000, 240000)
  BASE_LR: 0.002
  IMS_PER_BATCH: 4
  WARMUP_FACTOR: 0.01
